[package]
name = 'send-defi'
version = '1.0.0'
[dependencies.AptosFramework]
git = 'https://github.com/davidiw/aptos-core.git'
rev = 'conversions'
subdir = 'aptos-move/framework/aptos-framework'
[addresses]
admin = '0xedf2c8addd8c2d48f3975fc6171c5b654d730688036115bdb5746e2c791046e5'
